name: Norminette

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install norminette
        run: pip install norminette

      - name: Run norminette
        run: norminette
