name: Norminette

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install norminette
        run: pip install norminette

      - name: Run norminette
        run: norminette

      - name: Notify Discord
        if: env.DISCORD_WEBHOOK != ''
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: "Norminette: ${{ job.status }} on `${{ github.repository }}` (`${{ github.ref_name }}`)"
